export { IconLogo } from './IconLogo'
export { IconBars } from './IconBars'
export { IconMoon } from './IconMoon'
export { IconSun } from './IconSun'
export { IconClose } from './IconClose'
export { IconFile } from './IconFile'
export { IconUser } from './IconUser'
// export { IconDetalle } from './IconDetalle'
